type: object
properties:
  hosts:
    type: array
    uniqueItems: true
    items: 
      type: objects
      additionalProperties: false
      required:
        - hostname
        - version
        - modules
      properties:
        hostname:
          type: string
          format: hostname
        version:
          type: string
          enum: 
            - v1
            - v2
            - v2c
            - v3
        community:
          type: string
          default: public
        modules:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: string
  modules:
    type: object:
    minProperties: 1
    patternProperties:
      ".+":
        type: object
        additionalProperties: false
        properties:
          template_labels:
            type: object
            patternProperties:
              .+: 
                type: object
                additionalProperties: false
                properties:
                  type:
                    type: string
                    enum: 
                      - get
                      - walk
                  every:
                    type: string
                    pattern: '^[0-9]+[smhdwMy]$'
                    default: 1m
                  community_template:
                    type: string
                    default: "{{ community }}@{{ template }}"
                  mapping:
                    type: string
                required:
                  - type
                  - mapping
            default: {}
          labels:
            type: object
            patternProperties:
              .+:
                type: object
                additionalProperties: false
                properties:
                  type:
                    type: string
                    enum: 
                      - get
                      - walk
                  every:
                    type: string
                    pattern: '^[0-9]+[smhdwMy]$'
                    default: 1m
                  template_label:
                    type: string
                  mappings:
                    type: object
                    patternProperties:
                      .+: 
                        type: string
                    minProperties: 1
                required:
                  - type
                  - mappings
            default: {}
          metrics:
            type: list
            minItems: 1
            uniqueItems: true
            items: 
              type: object
              additionalProperties: false
              properties:
                type:
                  type: string
                  enum: 
                    - get
                    - walk
                every:
                  type: string
                  pattern: '^[0-9]+[smhdwMy]$'
                  default: 1m
                template_label:
                  type: string
                mappings:
                  type: dict
                  patternProperties:
                    .+: 
                      type: string
                append_tags:
                  type: list
                  items:
                    type: string
              required:
                - type
                - mappings
        required:
          - metrics
  description:
    type: object
    minProperties: 1
    patternProperties:
      .+: 
        type: object
        additionalProperties: false
        properties: 
          type:
            type: string
            enum: 
              - counter
              - gauge
              - histogram
              - summary
          description:
            type: string
        required: 
          - type
          - description
